"""Split reviewed Higgsfield atlases into offline choice-card images."""
from pathlib import Path
from PIL import Image
import base64
import json

ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / 'assets' / 'choices'
packed = {}
for atlas in json.loads((ASSETS / 'manifest.json').read_text(encoding='utf-8')):
    img = Image.open(ASSETS / (atlas['id'] + '.png')).convert('RGB')
    cw, ch = img.width / atlas['cols'], img.height / atlas['rows']
    for i, (key, description) in enumerate(atlas['cells']):
        if key.startswith('extra:'):
            continue
        col, row = i % atlas['cols'], i // atlas['cols']
        tile = img.crop((round(col * cw) + 4, round(row * ch) + 4,
                         round((col + 1) * cw) - 4, round((row + 1) * ch) - 4))
        replacement = ASSETS / (key.replace(':', '-') + '-override.png')
        if replacement.exists():
            tile = Image.open(replacement).convert('RGB')
        tile.thumbnail((480, 560) if key.startswith('d:') else (480, 320), Image.Resampling.LANCZOS)
        target = ASSETS / (key.replace(':', '-') + '.webp')
        tile.save(target, format='WEBP', quality=66, method=6)
        packed[key] = 'data:image/webp;base64,' + base64.b64encode(target.read_bytes()).decode('ascii')
(ROOT / 'src/ui/choice-art-data.js').write_text(
    '// Generated by tools/pack-choice-art.py; source and provenance: assets/choices/.\n'
    + 'export const CHOICE_ART = ' + json.dumps(packed, ensure_ascii=False, separators=(',', ':')) + '\n', encoding='utf-8')
print(len(packed), 'choice images;', sum(len(s) for s in packed.values()), 'embedded bytes')
