"""Generate and embed Korean narration, retaining word timing and reusable audio files."""
import asyncio
import base64
import json
import subprocess
from pathlib import Path
import edge_tts
import imageio_ffmpeg

ROOT = Path(__file__).resolve().parent.parent
CACHE = ROOT / 'tools/voice/narration'
VOICE = 'ko-KR-InJoonNeural'

async def main():
    lines = json.loads((CACHE / 'lines.json').read_text(encoding='utf-8'))
    semaphore = asyncio.Semaphore(3)
    async def generate(item):
        audio = CACHE / (item['key'] + '.mp3')
        timing = CACHE / (item['key'] + '.json')
        if audio.exists() and timing.exists():
            return
        async with semaphore:
            for attempt in range(3):
                try:
                    chunks, words = [], []
                    speech = edge_tts.Communicate(item['text'], VOICE, rate='-8%', boundary='WordBoundary')
                    async for chunk in speech.stream():
                        if chunk['type'] == 'audio': chunks.append(chunk['data'])
                        elif chunk['type'] == 'WordBoundary': words.append(chunk)
                    if not chunks or not words: raise RuntimeError('Missing audio or word timestamps')
                    audio.write_bytes(b''.join(chunks))
                    timing.write_text(json.dumps(words, ensure_ascii=False), encoding='utf-8')
                    print('recorded', item['key'], flush=True)
                    break
                except Exception:
                    if attempt == 2: raise
                    await asyncio.sleep(2 * (attempt + 1))
    await asyncio.gather(*(generate(item) for item in lines))
    clips = {}
    encoder = imageio_ffmpeg.get_ffmpeg_exe()
    for item in lines:
        words = json.loads((CACHE / (item['key'] + '.json')).read_text(encoding='utf-8'))
        line, at = item['line'], 0
        times = [None] * len(line)
        for word in words:
            start = word['offset'] / 10000
            duration = word['duration'] / 10000
            for index, ch in enumerate(word['text']):
                pos = line.find(ch, at)
                if pos < 0: continue
                times[pos] = round(start + duration * index / max(1, len(word['text'])))
                at = pos + 1
        last = 0
        for i, time in enumerate(times):
            last = max(last, time if time is not None else last)
            times[i] = last
        ms = round((words[-1]['offset'] + words[-1]['duration']) / 10000 + 300)
        compressed = CACHE / (item['key'] + '.ogg')
        if not compressed.exists():
            subprocess.run([encoder, '-hide_banner', '-loglevel', 'error', '-y', '-i', str(CACHE / (item['key'] + '.mp3')), '-c:a', 'libopus', '-b:a', '12k', '-application', 'voip', '-ac', '1', '-ar', '24000', str(compressed)], check=True)
        clips[item['key']] = {'src': 'data:audio/ogg;base64,' + base64.b64encode(compressed.read_bytes()).decode(), 'ms': ms, 't': times}
    (ROOT / 'src/data/narration-data.js').write_text('// Generated by tools/pack-narration.py; ko-KR-InJoonNeural, word-aligned narration.\nexport const NARRATION = ' + json.dumps(clips, ensure_ascii=False, separators=(',', ':')) + '\n', encoding='utf-8')
    print('Embedded', len(clips), 'narration clips', flush=True)

asyncio.run(main())
